# Chapter 21: Creating and Updating Columns

## 21.1 Loading the Data

In [1]:
import pandas as pd
import numpy as np
url = 'https://github.com/mattharrison/datasets/raw/master/data/2020-jetbrains-python-survey.csv'
jb = pd.read_csv(url)
jb

<ipython-input-1-ea8d9fd41914>:4: DtypeWarning: Columns (152) have mixed types. Specify dtype option on import or set low_memory=False.
  jb = pd.read_csv(url)

,is.python.main,other.lang.None,other.lang.Java,other.lang.JavaScript,other.lang.C/C++,other.lang.PHP,other.lang.C#,other.lang.Ruby,other.lang.Bash / Shell,other.lang.Objective-C,...,job.role.Technical support,job.role.Data analyst,job.role.Business analyst,job.role.Team lead,job.role.Product manager,job.role.CIO / CEO / CTO,job.role.Systems analyst,job.role.Other,age,country.live
0,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bash / Shell,NaN,...,NaN,NaN,Business analyst,NaN,NaN,NaN,NaN,NaN,30–39,NaN
1,Yes,NaN,Java,JavaScript,NaN,NaN,C#,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21–29,India
2,Yes,NaN,NaN,NaN,C/C++,NaN,NaN,NaN,Bash / Shell,NaN,...,Technical support,Data analyst,NaN,Team lead,NaN,NaN,NaN,NaN,30–39,United States
3,Yes,NaN,NaN,JavaScript,NaN,NaN,NaN,NaN,Bash / Shell,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Yes,NaN,Java,JavaScript,C/C++,NaN,NaN,NaN,Bash / Shell,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21–29,Italy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54457,Yes,NaN,NaN,NaN,C/C++,NaN,NaN,NaN,Bash / Shell,Objective-C,...,NaN,NaN,NaN,NaN,NaN,NaN,Systems analyst,NaN,21–29,Russian Federation
54458,Yes,NaN,NaN,JavaScript,NaN,NaN,NaN,NaN,Bash / Shell,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54459,Yes,NaN,NaN,JavaScript,NaN,PHP,NaN,NaN,Bash / Shell,NaN,...,NaN,NaN,NaN,NaN,NaN,CIO / CEO / CTO,NaN,NaN,21–29,Russian Federation
54460,Yes,NaN,NaN,JavaScript,C/C++,PHP,NaN,NaN,Bash / Shell,NaN,...,NaN,Data analyst,NaN,NaN,NaN,NaN,NaN,NaN,30–39,Spain
54461,Yes,NaN,NaN,JavaScript,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,Team lead,NaN,NaN,NaN,NaN,21–29,Algeria

In [2]:
jb.head()

,is.python.main,other.lang.None,other.lang.Java,other.lang.JavaScript,other.lang.C/C++,other.lang.PHP,other.lang.C#,other.lang.Ruby,other.lang.Bash / Shell,other.lang.Objective-C,...,job.role.Technical support,job.role.Data analyst,job.role.Business analyst,job.role.Team lead,job.role.Product manager,job.role.CIO / CEO / CTO,job.role.Systems analyst,job.role.Other,age,country.live
0,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bash / Shell,NaN,...,NaN,NaN,Business analyst,NaN,NaN,NaN,NaN,NaN,30–39,NaN
1,Yes,NaN,Java,JavaScript,NaN,NaN,C#,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21–29,India
2,Yes,NaN,NaN,NaN,C/C++,NaN,NaN,NaN,Bash / Shell,NaN,...,Technical support,Data analyst,NaN,Team lead,NaN,NaN,NaN,NaN,30–39,United States
3,Yes,NaN,NaN,JavaScript,NaN,NaN,NaN,NaN,Bash / Shell,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Yes,NaN,Java,JavaScript,C/C++,NaN,NaN,NaN,Bash / Shell,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21–29,Italy

In [3]:
jb.columns

Index(['is.python.main', 'other.lang.None', 'other.lang.Java',
       'other.lang.JavaScript', 'other.lang.C/C++', 'other.lang.PHP',
       'other.lang.C#', 'other.lang.Ruby', 'other.lang.Bash / Shell',
       'other.lang.Objective-C',
       ...
       'job.role.Technical support', 'job.role.Data analyst',
       'job.role.Business analyst', 'job.role.Team lead',
       'job.role.Product manager', 'job.role.CIO / CEO / CTO',
       'job.role.Systems analyst', 'job.role.Other', 'age', 'country.live'],
      dtype='object', length=264)

In [4]:
jb.shape

(54462, 264)

In [7]:
jb.dtypes.value_counts()

object     251
float64     13
Name: count, dtype: int64

In [9]:
jb.select_dtypes('float64').head(20)

,other.lang.None,isolate.environments.None,web.frameworks.None,data.frameworks.None,other.frameworks.None,cloud.platform.None,unittesting.None,database.None,bigdata.None,ci.None,configuration.management.None,ide.editor.None,nps.main.ide
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0
17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0
19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
jb.select_dtypes('float')

,other.lang.None,isolate.environments.None,web.frameworks.None,data.frameworks.None,other.frameworks.None,cloud.platform.None,unittesting.None,database.None,bigdata.None,ci.None,configuration.management.None,ide.editor.None,nps.main.ide
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
54457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0
54458,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54459,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0
54460,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0
54461,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0

In [11]:
jb.select_dtypes('float').dropna()

Empty DataFrame
Columns: [other.lang.None, isolate.environments.None, web.frameworks.None, data.frameworks.None, other.frameworks.None, cloud.platform.None, unittesting.None, database.None, bigdata.None, ci.None, configuration.management.None, ide.editor.None, nps.main.ide]
Index: []

In [12]:
jb.select_dtypes('float').dropna().head()

Empty DataFrame
Columns: [other.lang.None, isolate.environments.None, web.frameworks.None, data.frameworks.None, other.frameworks.None, cloud.platform.None, unittesting.None, database.None, bigdata.None, ci.None, configuration.management.None, ide.editor.None, nps.main.ide]
Index: []

In [17]:
jb.select_dtypes('float').dropna(axis= 'columns')

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, ...]

[54462 rows x 0 columns]

In [20]:
jb.select_dtypes('float').dropna(how='all')

,other.lang.None,isolate.environments.None,web.frameworks.None,data.frameworks.None,other.frameworks.None,cloud.platform.None,unittesting.None,database.None,bigdata.None,ci.None,configuration.management.None,ide.editor.None,nps.main.ide
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
54456,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0
54457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0
54459,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0
54460,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0
54461,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0

In [19]:
jb.select_dtypes('float')

,other.lang.None,isolate.environments.None,web.frameworks.None,data.frameworks.None,other.frameworks.None,cloud.platform.None,unittesting.None,database.None,bigdata.None,ci.None,configuration.management.None,ide.editor.None,nps.main.ide
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
54457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0
54458,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54459,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0
54460,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0
54461,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0

In [22]:
jb.select_dtypes('float').dropna(how='all', axis = 'rows')

,other.lang.None,isolate.environments.None,web.frameworks.None,data.frameworks.None,other.frameworks.None,cloud.platform.None,unittesting.None,database.None,bigdata.None,ci.None,configuration.management.None,ide.editor.None,nps.main.ide
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
54456,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0
54457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0
54459,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0
54460,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0
54461,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0

In [23]:
jb.select_dtypes('float').dropna(how='all', axis = 'columns')

       nps.main.ide
0               3.0
1               8.0
2              10.0
3              10.0
4              10.0
...             ...
54457          10.0
54458           NaN
54459          10.0
54460           3.0
54461          10.0

[54462 rows x 1 columns]

In [24]:
jb.select_dtypes('float').dropna(how='all', axis = 'columns').count()

nps.main.ide    25441
dtype: int64

In [61]:
jb.select_dtypes('float').dropna(how='all', axis = 'rows').count()

other.lang.None                      0
isolate.environments.None            0
web.frameworks.None                  0
data.frameworks.None                 0
other.frameworks.None                0
cloud.platform.None                  0
unittesting.None                     0
database.None                        0
bigdata.None                         0
ci.None                              0
configuration.management.None        0
ide.editor.None                      0
nps.main.ide                     25441
dtype: int64

In [62]:
jb.select_dtypes('float').dropna(how='all', axis = 'rows')

,other.lang.None,isolate.environments.None,web.frameworks.None,data.frameworks.None,other.frameworks.None,cloud.platform.None,unittesting.None,database.None,bigdata.None,ci.None,configuration.management.None,ide.editor.None,nps.main.ide
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
54456,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0
54457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0
54459,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0
54460,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0
54461,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0

In [63]:
jb.select_dtypes('float').dropna(how='all', axis = 'index')

,other.lang.None,isolate.environments.None,web.frameworks.None,data.frameworks.None,other.frameworks.None,cloud.platform.None,unittesting.None,database.None,bigdata.None,ci.None,configuration.management.None,ide.editor.None,nps.main.ide
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
54456,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0
54457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0
54459,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0
54460,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0
54461,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0

In [25]:
jb.select_dtypes('float').dropna(how='all', axis = 'columns').describe()

       nps.main.ide
count  25441.000000
mean       8.782281
std        1.631416
min        0.000000
25%        8.000000
50%        9.000000
75%       10.000000
max       10.000000

In [28]:
jb.select_dtypes('float').dropna(how='all', axis = 'columns').isna().sum()

nps.main.ide    29021
dtype: int64

In [ ]:
d = {'col1': [1,2,3], 'col2':[4,5,6]}

In [ ]:
df = pd.DataFrame(d)

In [ ]:
df

   col1  col2
0     1     4
1     2     5
2     3     6

In [ ]:
df.dtypes

col1    int64
col2    int64
dtype: object

In [ ]:
df.astype('float').dtypes

col1    float64
col2    float64
dtype: object

In [ ]:
df.astype({'col1':'int32'}).dtypes

col1    int32
col2    int64
dtype: object

In [29]:
jb.columns

Index(['is.python.main', 'other.lang.None', 'other.lang.Java',
       'other.lang.JavaScript', 'other.lang.C/C++', 'other.lang.PHP',
       'other.lang.C#', 'other.lang.Ruby', 'other.lang.Bash / Shell',
       'other.lang.Objective-C',
       ...
       'job.role.Technical support', 'job.role.Data analyst',
       'job.role.Business analyst', 'job.role.Team lead',
       'job.role.Product manager', 'job.role.CIO / CEO / CTO',
       'job.role.Systems analyst', 'job.role.Other', 'age', 'country.live'],
      dtype='object', length=264)

In [30]:
sorted(jb.columns)

['age',
 'are.you.datascientist',
 'bigdata.Apache Beam',
 'bigdata.Apache Flink',
 'bigdata.Apache Hadoop/MapReduce',
 'bigdata.Apache Hive',
 'bigdata.Apache Kafka',
 'bigdata.Apache Samza',
 'bigdata.Apache Spark',
 'bigdata.Apache Tez',
 'bigdata.ClickHouse',
 'bigdata.Dask',
 'bigdata.None',
 'bigdata.Other',
 'ci.AppVeyor',
 'ci.Bamboo',
 'ci.CircleCI',
 'ci.CruiseControl',
 'ci.Gitlab CI',
 'ci.Jenkins / Hudson',
 'ci.None',
 'ci.Other',
 'ci.TeamCity',
 'ci.Travis CI',
 'cloud.platform.AWS',
 'cloud.platform.DigitalOcean',
 'cloud.platform.Google Cloud Platform',
 'cloud.platform.Heroku',
 'cloud.platform.Linode',
 'cloud.platform.Microsoft Azure',
 'cloud.platform.None',
 'cloud.platform.OpenShift',
 'cloud.platform.OpenStack',
 'cloud.platform.Other',
 'cloud.platform.PythonAnywhere',
 'cloud.platform.Rackspace',
 'company.size',
 'configuration.management.Ansible',
 'configuration.management.Chef',
 'configuration.management.Custom solution',
 'configuration.management.None',
 'configuration.management.Other',
 'configuration.management.Puppet',
 'configuration.management.Salt',
 'country.live',
 'data.frameworks.Gensim',
 'data.frameworks.Keras',
 'data.frameworks.MXNet',
 'data.frameworks.Matplotlib',
 'data.frameworks.NLTK',
 'data.frameworks.None',
 'data.frameworks.NumPy',
 'data.frameworks.Other',
 'data.frameworks.Pandas',
 'data.frameworks.PyTorch',
 'data.frameworks.SciKit-Learn',
 'data.frameworks.SciPy',
 'data.frameworks.Seaborn',
 'data.frameworks.TensorFlow',
 'data.frameworks.Theano',
 'database.Amazon Redshift',
 'database.Cassandra',
 'database.Couchbase',
 'database.DB2',
 'database.HBase',
 'database.MS SQL Server',
 'database.MongoDB',
 'database.MySQL',
 'database.Neo4j',
 'database.None',
 'database.Oracle Database',
 'database.Other',
 'database.PostgreSQL',
 'database.Redis',
 'database.SQLite',
 'database.h2',
 'develop.for.cloud.Directly in the production environment',
 'develop.for.cloud.In Docker containers',
 'develop.for.cloud.In remote development environments',
 'develop.for.cloud.In virtual machines',
 'develop.for.cloud.Locally with virtualenv (or similar)',
 'develop.for.cloud.None of the following',
 'develop.for.cloud.Other',
 'develop.for.cloud.With local system interpreter',
 'devenv.os.BSD',
 'devenv.os.Linux',
 'devenv.os.Other',
 'devenv.os.Windows',
 'devenv.os.macOS',
 'employment.status',
 'first.learn.about.main.ide',
 'how.involved.Computer graphics',
 'how.involved.Data analysis',
 'how.involved.Desktop development',
 'how.involved.DevOps / System administration / Writing automation scripts',
 'how.involved.Educational purposes',
 'how.involved.Embedded development',
 'how.involved.Game development',
 'how.involved.Machine learning',
 'how.involved.Mobile development',
 'how.involved.Multimedia applications development',
 'how.involved.Network programming',
 'how.involved.Programming of web parsers / scrapers / crawlers',
 'how.involved.Software prototyping',
 'how.involved.Software testing / Writing automated tests',
 'how.involved.Web development',
 'how.often.use.main.ide',
 'ide.editor.Atom',
 'ide.editor.Eclipse + Pydev',
 'ide.editor.Emacs',
 'ide.editor.IDLE',
 'ide.editor.IntelliJ IDEA',
 'ide.editor.Jupyter Notebook',
 'ide.editor.JupyterLab',
 'ide.editor.None',
 'ide.editor.NotePad++',
 'ide.editor.Other',
 'ide.editor.PyCharm Community Edition',
 'ide.editor.PyCharm Professional Edition',
 'ide.editor.Python Tools for Visual Studio (PTVS)',
 'ide.editor.Spyder',
 'ide.editor.Sublime Text',
 'ide.editor.VS Code',
 'ide.editor.Vim',
 'ide.main',
 'is.python.main',
 'isolate.environments.Conda',
 'isolate.environments.Docker',
 'isolate.environments.None',
 'isolate.environments.Other',
 'isolate.environments.Pipenv',
 'isolate.environments.Poetry',
 'isolate.environments.Vagrant  / virtual machines',
 'isolate.environments.Virtualenv',
 'job.role.Architect',
 'job.role.Business analyst',
 'job.role.CIO / CEO / CTO',
 'job.role.DBA',
 'job.role.Data analyst',
 'job.role.Developer / Programmer',
 'job.role.Other',
 'job.role.Product manager',
 'job.role.QA engineer',
 'job.role.Systems analyst',
 'job.role.Team lead',
 'job.role.Technical support',
 'job.role.Technical writer',
 'job.team',
 'main.purposes',
 'missing.features.main.ide',
 'nps.main.ide',
 'orm.Dejavu',
 'orm.Django ORM',
 'orm.No database development',
 'orm.Other',
 'orm.Peewee',
 'orm.PonyORM',
 'orm.Raw SQL',
 'orm.SQLAlchemy',
 'orm.SQLObject',
 'orm.Tortoise ORM',
 'other.frameworks.Asyncio',
 'other.frameworks.Kivy',
 'other.frameworks.None',
 'other.frameworks.Other',
 'other.frameworks.Pillow',
 'other.frameworks.PyGTK',
 'other.frameworks.PyQT',
 'other.frameworks.Pygame',
 'other.frameworks.Requests',
 'other.frameworks.Scrapy',
 'other.frameworks.Six',
 'other.frameworks.Tkinter',
 'other.frameworks.Twisted',
 'other.frameworks.aiohttp',
 'other.frameworks.wxPython',
 'other.lang.Bash / Shell',
 'other.lang.C#',
 'other.lang.C/C++',
 'other.lang.Clojure',
 'other.lang.CoffeeScript',
 'other.lang.Go',
 'other.lang.Groovy',
 'other.lang.HTML/CSS',
 'other.lang.Java',
 'other.lang.JavaScript',
 'other.lang.Kotlin',
 'other.lang.None',
 'other.lang.Objective-C',
 'other.lang.Other',
 'other.lang.PHP',
 'other.lang.Perl',
 'other.lang.R',
 'other.lang.Ruby',
 'other.lang.Rust',
 'other.lang.SQL',
 'other.lang.Scala',
 'other.lang.Swift',
 'other.lang.TypeScript',
 'other.lang.Visual Basic',
 'other.purposes.Computer graphics',
 'other.purposes.Data analysis',
 'other.purposes.Desktop development',
 'other.purposes.DevOps / System administration / Writing automation scripts',
 'other.purposes.Educational purposes',
 'other.purposes.Embedded development',
 'other.purposes.Game development',
 'other.purposes.Machine learning',
 'other.purposes.Mobile development',
 'other.purposes.Multimedia applications development',
 'other.purposes.Network programming',
 'other.purposes.Other',
 'other.purposes.Programming of web parsers / scrapers / crawlers',
 'other.purposes.Software prototyping',
 'other.purposes.Software testing / Writing automated tests',
 'other.purposes.Web development',
 'python.version.most',
 'python.version.upgrade.ActivePython',
 'python.version.upgrade.Anaconda',
 'python.version.upgrade.Automatic upgrade via cloud provider',
 'python.version.upgrade.Build from source',
 'python.version.upgrade.I don’t update',
 'python.version.upgrade.I use Docker containers',
 'python.version.upgrade.Intel Distribution for Python',
 'python.version.upgrade.OS-provided Python (via apt-get, yum, homebrew, etc_)',
 'python.version.upgrade.Other',
 'python.version.upgrade.Python_org',
 'python.version.upgrade.Somebody else manages Python updates for me',
 'python.version.upgrade.pyenv',
 'python.version.upgrade.pythonz',
 'python.years',
 'python2.version.most',
 'python3.version.most',
 'run.in.cloud.In virtual machines',
 'run.in.cloud.None of the following',
 'run.in.cloud.On a Platform-as-a-Service (such as Heroku or Google App Engine)',
 'run.in.cloud.Other',
 'run.in.cloud.Serverless (such as AWS Lambda or Cloud Functions)',
 'run.in.cloud.Within containers',
 'several.projects',
 'team.size',
 'unittesting.Hypothesis',
 'unittesting.None',
 'unittesting.Other',
 'unittesting.Tox',
 'unittesting.doctest',
 'unittesting.mock',
 'unittesting.nose',
 'unittesting.pytest',
 'unittesting.unittest',
 'use.python.most',
 'web.frameworks.Bottle',
 'web.frameworks.CherryPy\xa0',
 'web.frameworks.Django',
 'web.frameworks.Falcon',
 'web.frameworks.FastAPI',
 'web.frameworks.Flask\xa0',
 'web.frameworks.Hug',
 'web.frameworks.None',
 'web.frameworks.Other',
 'web.frameworks.Pyramid\xa0',
 'web.frameworks.Tornado',
 'web.frameworks.web2py',
 'years.of.coding']

In [31]:
'years.of.coding'.count('.')

2

In [38]:
'.'.join('a.b.c.c'.split('.')[:2])

'a.b'

In [41]:
import collections
counter = collections.defaultdict(list)

In [47]:
counter['.'.join('a.b.c.c'.split('.')[:2])].append('a.b.c.c')

In [48]:
counter['.'.join('a.b.c.c'.split('.')[:2])]

['a.b.c.c', 'a.b.c.c', 'a.b.c.c', 'a.b.c.c']

- Determine whether a feature can be multiple values and removes those

In [49]:
import collections
counter = collections.defaultdict(list)

for col in sorted(jb.columns):
    period_count = col.count('.')
    if period_count >= 2:
        part_end = 2
    else:
        part_end = 1

    parts = col.split('.')[:part_end]
    counter['.'.join(parts)].append(col)

In [50]:
counter

defaultdict(list,
            {'age': ['age'],
             'are.you': ['are.you.datascientist'],
             'bigdata': ['bigdata.Apache Beam',
              'bigdata.Apache Flink',
              'bigdata.Apache Hadoop/MapReduce',
              'bigdata.Apache Hive',
              'bigdata.Apache Kafka',
              'bigdata.Apache Samza',
              'bigdata.Apache Spark',
              'bigdata.Apache Tez',
              'bigdata.ClickHouse',
              'bigdata.Dask',
              'bigdata.None',
              'bigdata.Other'],
             'ci': ['ci.AppVeyor',
              'ci.Bamboo',
              'ci.CircleCI',
              'ci.CruiseControl',
              'ci.Gitlab CI',
              'ci.Jenkins / Hudson',
              'ci.None',
              'ci.Other',
              'ci.TeamCity',
              'ci.Travis CI'],
             'cloud.platform': ['cloud.platform.AWS',
              'cloud.platform.DigitalOcean',
              'cloud.platform.Google Cloud Platform',
              'cloud.platform.Heroku',
              'cloud.platform.Linode',
              'cloud.platform.Microsoft Azure',
              'cloud.platform.None',
              'cloud.platform.OpenShift',
              'cloud.platform.OpenStack',
              'cloud.platform.Other',
              'cloud.platform.PythonAnywhere',
              'cloud.platform.Rackspace'],
             'company': ['company.size'],
             'configuration.management': ['configuration.management.Ansible',
              'configuration.management.Chef',
              'configuration.management.Custom solution',
              'configuration.management.None',
              'configuration.management.Other',
              'configuration.management.Puppet',
              'configuration.management.Salt'],
             'country': ['country.live'],
             'data.frameworks': ['data.frameworks.Gensim',
              'data.frameworks.Keras',
              'data.frameworks.MXNet',
              'data.frameworks.Matplotlib',
              'data.frameworks.NLTK',
              'data.frameworks.None',
              'data.frameworks.NumPy',
              'data.frameworks.Other',
              'data.frameworks.Pandas',
              'data.frameworks.PyTorch',
              'data.frameworks.SciKit-Learn',
              'data.frameworks.SciPy',
              'data.frameworks.Seaborn',
              'data.frameworks.TensorFlow',
              'data.frameworks.Theano'],
             'database': ['database.Amazon Redshift',
              'database.Cassandra',
              'database.Couchbase',
              'database.DB2',
              'database.HBase',
              'database.MS SQL Server',
              'database.MongoDB',
              'database.MySQL',
              'database.Neo4j',
              'database.None',
              'database.Oracle Database',
              'database.Other',
              'database.PostgreSQL',
              'database.Redis',
              'database.SQLite',
              'database.h2'],
             'develop.for': ['develop.for.cloud.Directly in the production environment',
              'develop.for.cloud.In Docker containers',
              'develop.for.cloud.In remote development environments',
              'develop.for.cloud.In virtual machines',
              'develop.for.cloud.Locally with virtualenv (or similar)',
              'develop.for.cloud.None of the following',
              'develop.for.cloud.Other',
              'develop.for.cloud.With local system interpreter'],
             'devenv.os': ['devenv.os.BSD',
              'devenv.os.Linux',
              'devenv.os.Other',
              'devenv.os.Windows',
              'devenv.os.macOS'],
             'employment': ['employment.status'],
             'first.learn': ['first.learn.about.main.ide'],
             'how.involved': ['how.involved.Computer graphics',
              'how.involved.Data analysis',
              'how.involved.Desktop development',
              'how.involved.DevOps / System administration / Writing automation scripts',
              'how.involved.Educational purposes',
              'how.involved.Embedded development',
              'how.involved.Game development',
              'how.involved.Machine learning',
              'how.involved.Mobile development',
              'how.involved.Multimedia applications development',
              'how.involved.Network programming',
              'how.involved.Programming of web parsers / scrapers / crawlers',
              'how.involved.Software prototyping',
              'how.involved.Software testing / Writing automated tests',
              'how.involved.Web development'],
             'how.often': ['how.often.use.main.ide'],
             'ide.editor': ['ide.editor.Atom',
              'ide.editor.Eclipse + Pydev',
              'ide.editor.Emacs',
              'ide.editor.IDLE',
              'ide.editor.IntelliJ IDEA',
              'ide.editor.Jupyter Notebook',
              'ide.editor.JupyterLab',
              'ide.editor.None',
              'ide.editor.NotePad++',
              'ide.editor.Other',
              'ide.editor.PyCharm Community Edition',
              'ide.editor.PyCharm Professional Edition',
              'ide.editor.Python Tools for Visual Studio (PTVS)',
              'ide.editor.Spyder',
              'ide.editor.Sublime Text',
              'ide.editor.VS Code',
              'ide.editor.Vim'],
             'ide': ['ide.main'],
             'is.python': ['is.python.main'],
             'isolate.environments': ['isolate.environments.Conda',
              'isolate.environments.Docker',
              'isolate.environments.None',
              'isolate.environments.Other',
              'isolate.environments.Pipenv',
              'isolate.environments.Poetry',
              'isolate.environments.Vagrant  / virtual machines',
              'isolate.environments.Virtualenv'],
             'job.role': ['job.role.Architect',
              'job.role.Business analyst',
              'job.role.CIO / CEO / CTO',
              'job.role.DBA',
              'job.role.Data analyst',
              'job.role.Developer / Programmer',
              'job.role.Other',
              'job.role.Product manager',
              'job.role.QA engineer',
              'job.role.Systems analyst',
              'job.role.Team lead',
              'job.role.Technical support',
              'job.role.Technical writer'],
             'job': ['job.team'],
             'main': ['main.purposes'],
             'missing.features': ['missing.features.main.ide'],
             'nps.main': ['nps.main.ide'],
             'orm': ['orm.Dejavu',
              'orm.Django ORM',
              'orm.No database development',
              'orm.Other',
              'orm.Peewee',
              'orm.PonyORM',
              'orm.Raw SQL',
              'orm.SQLAlchemy',
              'orm.SQLObject',
              'orm.Tortoise ORM'],
             'other.frameworks': ['other.frameworks.Asyncio',
              'other.frameworks.Kivy',
              'other.frameworks.None',
              'other.frameworks.Other',
              'other.frameworks.Pillow',
              'other.frameworks.PyGTK',
              'other.frameworks.PyQT',
              'other.frameworks.Pygame',
              'other.frameworks.Requests',
              'other.frameworks.Scrapy',
              'other.frameworks.Six',
              'other.frameworks.Tkinter',
              'other.frameworks.Twisted',
              'other.frameworks.aiohttp',
              'other.frameworks.wxPython'],
             'other.lang': ['other.lang.Bash / Shell',
              'other.lang.C#',
              'other.lang.C/C++',
              'other.lang.Clojure',
              'other.lang.CoffeeScript',
              'other.lang.Go',
              'other.lang.Groovy',
              'other.lang.HTML/CSS',
              'other.lang.Java',
              'other.lang.JavaScript',
              'other.lang.Kotlin',
              'other.lang.None',
              'other.lang.Objective-C',
              'other.lang.Other',
              'other.lang.PHP',
              'other.lang.Perl',
              'other.lang.R',
              'other.lang.Ruby',
              'other.lang.Rust',
              'other.lang.SQL',
              'other.lang.Scala',
              'other.lang.Swift',
              'other.lang.TypeScript',
              'other.lang.Visual Basic'],
             'other.purposes': ['other.purposes.Computer graphics',
              'other.purposes.Data analysis',
              'other.purposes.Desktop development',
              'other.purposes.DevOps / System administration / Writing automation scripts',
              'other.purposes.Educational purposes',
              'other.purposes.Embedded development',
              'other.purposes.Game development',
              'other.purposes.Machine learning',
              'other.purposes.Mobile development',
              'other.purposes.Multimedia applications development',
              'other.purposes.Network programming',
              'other.purposes.Other',
              'other.purposes.Programming of web parsers / scrapers / crawlers',
              'other.purposes.Software prototyping',
              'other.purposes.Software testing / Writing automated tests',
              'other.purposes.Web development'],
             'python.version': ['python.version.most',
              'python.version.upgrade.ActivePython',
              'python.version.upgrade.Anaconda',
              'python.version.upgrade.Automatic upgrade via cloud provider',
              'python.version.upgrade.Build from source',
              'python.version.upgrade.I don’t update',
              'python.version.upgrade.I use Docker containers',
              'python.version.upgrade.Intel Distribution for Python',
              'python.version.upgrade.OS-provided Python (via apt-get, yum, homebrew, etc_)',
              'python.version.upgrade.Other',
              'python.version.upgrade.Python_org',
              'python.version.upgrade.Somebody else manages Python updates for me',
              'python.version.upgrade.pyenv',
              'python.version.upgrade.pythonz'],
             'python': ['python.years'],
             'python2.version': ['python2.version.most'],
             'python3.version': ['python3.version.most'],
             'run.in': ['run.in.cloud.In virtual machines',
              'run.in.cloud.None of the following',
              'run.in.cloud.On a Platform-as-a-Service (such as Heroku or Google App Engine)',
              'run.in.cloud.Other',
              'run.in.cloud.Serverless (such as AWS Lambda or Cloud Functions)',
              'run.in.cloud.Within containers'],
             'several': ['several.projects'],
             'team': ['team.size'],
             'unittesting': ['unittesting.Hypothesis',
              'unittesting.None',
              'unittesting.Other',
              'unittesting.Tox',
              'unittesting.doctest',
              'unittesting.mock',
              'unittesting.nose',
              'unittesting.pytest',
              'unittesting.unittest'],
             'use.python': ['use.python.most'],
             'web.frameworks': ['web.frameworks.Bottle',
              'web.frameworks.CherryPy\xa0',
              'web.frameworks.Django',
              'web.frameworks.Falcon',
              'web.frameworks.FastAPI',
              'web.frameworks.Flask\xa0',
              'web.frameworks.Hug',
              'web.frameworks.None',
              'web.frameworks.Other',
              'web.frameworks.Pyramid\xa0',
              'web.frameworks.Tornado',
              'web.frameworks.web2py'],
             'years.of': ['years.of.coding']})

In [ ]:
counter

defaultdict(list,
            {'age': ['age'],
             'are.you': ['are.you.datascientist'],
             'bigdata': ['bigdata.Apache Beam',
              'bigdata.Apache Flink',
              'bigdata.Apache Hadoop/MapReduce',
              'bigdata.Apache Hive',
              'bigdata.Apache Kafka',
              'bigdata.Apache Samza',
              'bigdata.Apache Spark',
              'bigdata.Apache Tez',
              'bigdata.ClickHouse',
              'bigdata.Dask',
              'bigdata.None',
              'bigdata.Other'],
             'ci': ['ci.AppVeyor',
              'ci.Bamboo',
              'ci.CircleCI',
              'ci.CruiseControl',
              'ci.Gitlab CI',
              'ci.Jenkins / Hudson',
              'ci.None',
              'ci.Other',
              'ci.TeamCity',
              'ci.Travis CI'],
             'cloud.platform': ['cloud.platform.AWS',
              'cloud.platform.DigitalOcean',
              'cloud.platform.Google Cloud Platform',
              'cloud.platform.Heroku',
              'cloud.platform.Linode',
              'cloud.platform.Microsoft Azure',
              'cloud.platform.None',
              'cloud.platform.OpenShift',
              'cloud.platform.OpenStack',
              'cloud.platform.Other',
              'cloud.platform.PythonAnywhere',
              'cloud.platform.Rackspace'],
             'company': ['company.size'],
             'configuration.management': ['configuration.management.Ansible',
              'configuration.management.Chef',
              'configuration.management.Custom solution',
              'configuration.management.None',
              'configuration.management.Other',
              'configuration.management.Puppet',
              'configuration.management.Salt'],
             'country': ['country.live'],
             'data.frameworks': ['data.frameworks.Gensim',
              'data.frameworks.Keras',
              'data.frameworks.MXNet',
              'data.frameworks.Matplotlib',
              'data.frameworks.NLTK',
              'data.frameworks.None',
              'data.frameworks.NumPy',
              'data.frameworks.Other',
              'data.frameworks.Pandas',
              'data.frameworks.PyTorch',
              'data.frameworks.SciKit-Learn',
              'data.frameworks.SciPy',
              'data.frameworks.Seaborn',
              'data.frameworks.TensorFlow',
              'data.frameworks.Theano'],
             'database': ['database.Amazon Redshift',
              'database.Cassandra',
              'database.Couchbase',
              'database.DB2',
              'database.HBase',
              'database.MS SQL Server',
              'database.MongoDB',
              'database.MySQL',
              'database.Neo4j',
              'database.None',
              'database.Oracle Database',
              'database.Other',
              'database.PostgreSQL',
              'database.Redis',
              'database.SQLite',
              'database.h2'],
             'develop.for': ['develop.for.cloud.Directly in the production environment',
              'develop.for.cloud.In Docker containers',
              'develop.for.cloud.In remote development environments',
              'develop.for.cloud.In virtual machines',
              'develop.for.cloud.Locally with virtualenv (or similar)',
              'develop.for.cloud.None of the following',
              'develop.for.cloud.Other',
              'develop.for.cloud.With local system interpreter'],
             'devenv.os': ['devenv.os.BSD',
              'devenv.os.Linux',
              'devenv.os.Other',
              'devenv.os.Windows',
              'devenv.os.macOS'],
             'employment': ['employment.status'],
             'first.learn': ['first.learn.about.main.ide'],
             'how.involved': ['how.involved.Computer graphics',
              'how.involved.Data analysis',
              'how.involved.Desktop development',
              'how.involved.DevOps / System administration / Writing automation scripts',
              'how.involved.Educational purposes',
              'how.involved.Embedded development',
              'how.involved.Game development',
              'how.involved.Machine learning',
              'how.involved.Mobile development',
              'how.involved.Multimedia applications development',
              'how.involved.Network programming',
              'how.involved.Programming of web parsers / scrapers / crawlers',
              'how.involved.Software prototyping',
              'how.involved.Software testing / Writing automated tests',
              'how.involved.Web development'],
             'how.often': ['how.often.use.main.ide'],
             'ide.editor': ['ide.editor.Atom',
              'ide.editor.Eclipse + Pydev',
              'ide.editor.Emacs',
              'ide.editor.IDLE',
              'ide.editor.IntelliJ IDEA',
              'ide.editor.Jupyter Notebook',
              'ide.editor.JupyterLab',
              'ide.editor.None',
              'ide.editor.NotePad++',
              'ide.editor.Other',
              'ide.editor.PyCharm Community Edition',
              'ide.editor.PyCharm Professional Edition',
              'ide.editor.Python Tools for Visual Studio (PTVS)',
              'ide.editor.Spyder',
              'ide.editor.Sublime Text',
              'ide.editor.VS Code',
              'ide.editor.Vim'],
             'ide': ['ide.main'],
             'is.python': ['is.python.main'],
             'isolate.environments': ['isolate.environments.Conda',
              'isolate.environments.Docker',
              'isolate.environments.None',
              'isolate.environments.Other',
              'isolate.environments.Pipenv',
              'isolate.environments.Poetry',
              'isolate.environments.Vagrant  / virtual machines',
              'isolate.environments.Virtualenv'],
             'job.role': ['job.role.Architect',
              'job.role.Business analyst',
              'job.role.CIO / CEO / CTO',
              'job.role.DBA',
              'job.role.Data analyst',
              'job.role.Developer / Programmer',
              'job.role.Other',
              'job.role.Product manager',
              'job.role.QA engineer',
              'job.role.Systems analyst',
              'job.role.Team lead',
              'job.role.Technical support',
              'job.role.Technical writer'],
             'job': ['job.team'],
             'main': ['main.purposes'],
             'missing.features': ['missing.features.main.ide'],
             'nps.main': ['nps.main.ide'],
             'orm': ['orm.Dejavu',
              'orm.Django ORM',
              'orm.No database development',
              'orm.Other',
              'orm.Peewee',
              'orm.PonyORM',
              'orm.Raw SQL',
              'orm.SQLAlchemy',
              'orm.SQLObject',
              'orm.Tortoise ORM'],
             'other.frameworks': ['other.frameworks.Asyncio',
              'other.frameworks.Kivy',
              'other.frameworks.None',
              'other.frameworks.Other',
              'other.frameworks.Pillow',
              'other.frameworks.PyGTK',
              'other.frameworks.PyQT',
              'other.frameworks.Pygame',
              'other.frameworks.Requests',
              'other.frameworks.Scrapy',
              'other.frameworks.Six',
              'other.frameworks.Tkinter',
              'other.frameworks.Twisted',
              'other.frameworks.aiohttp',
              'other.frameworks.wxPython'],
             'other.lang': ['other.lang.Bash / Shell',
              'other.lang.C#',
              'other.lang.C/C++',
              'other.lang.Clojure',
              'other.lang.CoffeeScript',
              'other.lang.Go',
              'other.lang.Groovy',
              'other.lang.HTML/CSS',
              'other.lang.Java',
              'other.lang.JavaScript',
              'other.lang.Kotlin',
              'other.lang.None',
              'other.lang.Objective-C',
              'other.lang.Other',
              'other.lang.PHP',
              'other.lang.Perl',
              'other.lang.R',
              'other.lang.Ruby',
              'other.lang.Rust',
              'other.lang.SQL',
              'other.lang.Scala',
              'other.lang.Swift',
              'other.lang.TypeScript',
              'other.lang.Visual Basic'],
             'other.purposes': ['other.purposes.Computer graphics',
              'other.purposes.Data analysis',
              'other.purposes.Desktop development',
              'other.purposes.DevOps / System administration / Writing automation scripts',
              'other.purposes.Educational purposes',
              'other.purposes.Embedded development',
              'other.purposes.Game development',
              'other.purposes.Machine learning',
              'other.purposes.Mobile development',
              'other.purposes.Multimedia applications development',
              'other.purposes.Network programming',
              'other.purposes.Other',
              'other.purposes.Programming of web parsers / scrapers / crawlers',
              'other.purposes.Software prototyping',
              'other.purposes.Software testing / Writing automated tests',
              'other.purposes.Web development'],
             'python.version': ['python.version.most',
              'python.version.upgrade.ActivePython',
              'python.version.upgrade.Anaconda',
              'python.version.upgrade.Automatic upgrade via cloud provider',
              'python.version.upgrade.Build from source',
              'python.version.upgrade.I don’t update',
              'python.version.upgrade.I use Docker containers',
              'python.version.upgrade.Intel Distribution for Python',
              'python.version.upgrade.OS-provided Python (via apt-get, yum, homebrew, etc_)',
              'python.version.upgrade.Other',
              'python.version.upgrade.Python_org',
              'python.version.upgrade.Somebody else manages Python updates for me',
              'python.version.upgrade.pyenv',
              'python.version.upgrade.pythonz'],
             'python': ['python.years'],
             'python2.version': ['python2.version.most'],
             'python3.version': ['python3.version.most'],
             'run.in': ['run.in.cloud.In virtual machines',
              'run.in.cloud.None of the following',
              'run.in.cloud.On a Platform-as-a-Service (such as Heroku or Google App Engine)',
              'run.in.cloud.Other',
              'run.in.cloud.Serverless (such as AWS Lambda or Cloud Functions)',
              'run.in.cloud.Within containers'],
             'several': ['several.projects'],
             'team': ['team.size'],
             'unittesting': ['unittesting.Hypothesis',
              'unittesting.None',
              'unittesting.Other',
              'unittesting.Tox',
              'unittesting.doctest',
              'unittesting.mock',
              'unittesting.nose',
              'unittesting.pytest',
              'unittesting.unittest'],
             'use.python': ['use.python.most'],
             'web.frameworks': ['web.frameworks.Bottle',
              'web.frameworks.CherryPy\xa0',
              'web.frameworks.Django',
              'web.frameworks.Falcon',
              'web.frameworks.FastAPI',
              'web.frameworks.Flask\xa0',
              'web.frameworks.Hug',
              'web.frameworks.None',
              'web.frameworks.Other',
              'web.frameworks.Pyramid\xa0',
              'web.frameworks.Tornado',
              'web.frameworks.web2py'],
             'years.of': ['years.of.coding']})

In [52]:
counter.keys()

dict_keys(['age', 'are.you', 'bigdata', 'ci', 'cloud.platform', 'company', 'configuration.management', 'country', 'data.frameworks', 'database', 'develop.for', 'devenv.os', 'employment', 'first.learn', 'how.involved', 'how.often', 'ide.editor', 'ide', 'is.python', 'isolate.environments', 'job.role', 'job', 'main', 'missing.features', 'nps.main', 'orm', 'other.frameworks', 'other.lang', 'other.purposes', 'python.version', 'python', 'python2.version', 'python3.version', 'run.in', 'several', 'team', 'unittesting', 'use.python', 'web.frameworks', 'years.of'])

In [53]:
counter.values()

dict_values([['age'], ['are.you.datascientist'], ['bigdata.Apache Beam', 'bigdata.Apache Flink', 'bigdata.Apache Hadoop/MapReduce', 'bigdata.Apache Hive', 'bigdata.Apache Kafka', 'bigdata.Apache Samza', 'bigdata.Apache Spark', 'bigdata.Apache Tez', 'bigdata.ClickHouse', 'bigdata.Dask', 'bigdata.None', 'bigdata.Other'], ['ci.AppVeyor', 'ci.Bamboo', 'ci.CircleCI', 'ci.CruiseControl', 'ci.Gitlab CI', 'ci.Jenkins / Hudson', 'ci.None', 'ci.Other', 'ci.TeamCity', 'ci.Travis CI'], ['cloud.platform.AWS', 'cloud.platform.DigitalOcean', 'cloud.platform.Google Cloud Platform', 'cloud.platform.Heroku', 'cloud.platform.Linode', 'cloud.platform.Microsoft Azure', 'cloud.platform.None', 'cloud.platform.OpenShift', 'cloud.platform.OpenStack', 'cloud.platform.Other', 'cloud.platform.PythonAnywhere', 'cloud.platform.Rackspace'], ['company.size'], ['configuration.management.Ansible', 'configuration.management.Chef', 'configuration.management.Custom solution', 'configuration.management.None', 'configuration.management.Other', 'configuration.management.Puppet', 'configuration.management.Salt'], ['country.live'], ['data.frameworks.Gensim', 'data.frameworks.Keras', 'data.frameworks.MXNet', 'data.frameworks.Matplotlib', 'data.frameworks.NLTK', 'data.frameworks.None', 'data.frameworks.NumPy', 'data.frameworks.Other', 'data.frameworks.Pandas', 'data.frameworks.PyTorch', 'data.frameworks.SciKit-Learn', 'data.frameworks.SciPy', 'data.frameworks.Seaborn', 'data.frameworks.TensorFlow', 'data.frameworks.Theano'], ['database.Amazon Redshift', 'database.Cassandra', 'database.Couchbase', 'database.DB2', 'database.HBase', 'database.MS SQL Server', 'database.MongoDB', 'database.MySQL', 'database.Neo4j', 'database.None', 'database.Oracle Database', 'database.Other', 'database.PostgreSQL', 'database.Redis', 'database.SQLite', 'database.h2'], ['develop.for.cloud.Directly in the production environment', 'develop.for.cloud.In Docker containers', 'develop.for.cloud.In remote development environments', 'develop.for.cloud.In virtual machines', 'develop.for.cloud.Locally with virtualenv (or similar)', 'develop.for.cloud.None of the following', 'develop.for.cloud.Other', 'develop.for.cloud.With local system interpreter'], ['devenv.os.BSD', 'devenv.os.Linux', 'devenv.os.Other', 'devenv.os.Windows', 'devenv.os.macOS'], ['employment.status'], ['first.learn.about.main.ide'], ['how.involved.Computer graphics', 'how.involved.Data analysis', 'how.involved.Desktop development', 'how.involved.DevOps / System administration / Writing automation scripts', 'how.involved.Educational purposes', 'how.involved.Embedded development', 'how.involved.Game development', 'how.involved.Machine learning', 'how.involved.Mobile development', 'how.involved.Multimedia applications development', 'how.involved.Network programming', 'how.involved.Programming of web parsers / scrapers / crawlers', 'how.involved.Software prototyping', 'how.involved.Software testing / Writing automated tests', 'how.involved.Web development'], ['how.often.use.main.ide'], ['ide.editor.Atom', 'ide.editor.Eclipse + Pydev', 'ide.editor.Emacs', 'ide.editor.IDLE', 'ide.editor.IntelliJ IDEA', 'ide.editor.Jupyter Notebook', 'ide.editor.JupyterLab', 'ide.editor.None', 'ide.editor.NotePad++', 'ide.editor.Other', 'ide.editor.PyCharm Community Edition', 'ide.editor.PyCharm Professional Edition', 'ide.editor.Python Tools for Visual Studio (PTVS)', 'ide.editor.Spyder', 'ide.editor.Sublime Text', 'ide.editor.VS Code', 'ide.editor.Vim'], ['ide.main'], ['is.python.main'], ['isolate.environments.Conda', 'isolate.environments.Docker', 'isolate.environments.None', 'isolate.environments.Other', 'isolate.environments.Pipenv', 'isolate.environments.Poetry', 'isolate.environments.Vagrant  / virtual machines', 'isolate.environments.Virtualenv'], ['job.role.Architect', 'job.role.Business analyst', 'job.role.CIO / CEO / CTO', 'job.role.DBA', 'job.role.Data analyst', 'job.role.Developer / Programmer', 'job.role.Other', 'job.role.Product manager', 'job.role.QA engineer', 'job.role.Systems analyst', 'job.role.Team lead', 'job.role.Technical support', 'job.role.Technical writer'], ['job.team'], ['main.purposes'], ['missing.features.main.ide'], ['nps.main.ide'], ['orm.Dejavu', 'orm.Django ORM', 'orm.No database development', 'orm.Other', 'orm.Peewee', 'orm.PonyORM', 'orm.Raw SQL', 'orm.SQLAlchemy', 'orm.SQLObject', 'orm.Tortoise ORM'], ['other.frameworks.Asyncio', 'other.frameworks.Kivy', 'other.frameworks.None', 'other.frameworks.Other', 'other.frameworks.Pillow', 'other.frameworks.PyGTK', 'other.frameworks.PyQT', 'other.frameworks.Pygame', 'other.frameworks.Requests', 'other.frameworks.Scrapy', 'other.frameworks.Six', 'other.frameworks.Tkinter', 'other.frameworks.Twisted', 'other.frameworks.aiohttp', 'other.frameworks.wxPython'], ['other.lang.Bash / Shell', 'other.lang.C#', 'other.lang.C/C++', 'other.lang.Clojure', 'other.lang.CoffeeScript', 'other.lang.Go', 'other.lang.Groovy', 'other.lang.HTML/CSS', 'other.lang.Java', 'other.lang.JavaScript', 'other.lang.Kotlin', 'other.lang.None', 'other.lang.Objective-C', 'other.lang.Other', 'other.lang.PHP', 'other.lang.Perl', 'other.lang.R', 'other.lang.Ruby', 'other.lang.Rust', 'other.lang.SQL', 'other.lang.Scala', 'other.lang.Swift', 'other.lang.TypeScript', 'other.lang.Visual Basic'], ['other.purposes.Computer graphics', 'other.purposes.Data analysis', 'other.purposes.Desktop development', 'other.purposes.DevOps / System administration / Writing automation scripts', 'other.purposes.Educational purposes', 'other.purposes.Embedded development', 'other.purposes.Game development', 'other.purposes.Machine learning', 'other.purposes.Mobile development', 'other.purposes.Multimedia applications development', 'other.purposes.Network programming', 'other.purposes.Other', 'other.purposes.Programming of web parsers / scrapers / crawlers', 'other.purposes.Software prototyping', 'other.purposes.Software testing / Writing automated tests', 'other.purposes.Web development'], ['python.version.most', 'python.version.upgrade.ActivePython', 'python.version.upgrade.Anaconda', 'python.version.upgrade.Automatic upgrade via cloud provider', 'python.version.upgrade.Build from source', 'python.version.upgrade.I don’t update', 'python.version.upgrade.I use Docker containers', 'python.version.upgrade.Intel Distribution for Python', 'python.version.upgrade.OS-provided Python (via apt-get, yum, homebrew, etc_)', 'python.version.upgrade.Other', 'python.version.upgrade.Python_org', 'python.version.upgrade.Somebody else manages Python updates for me', 'python.version.upgrade.pyenv', 'python.version.upgrade.pythonz'], ['python.years'], ['python2.version.most'], ['python3.version.most'], ['run.in.cloud.In virtual machines', 'run.in.cloud.None of the following', 'run.in.cloud.On a Platform-as-a-Service (such as Heroku or Google App Engine)', 'run.in.cloud.Other', 'run.in.cloud.Serverless (such as AWS Lambda or Cloud Functions)', 'run.in.cloud.Within containers'], ['several.projects'], ['team.size'], ['unittesting.Hypothesis', 'unittesting.None', 'unittesting.Other', 'unittesting.Tox', 'unittesting.doctest', 'unittesting.mock', 'unittesting.nose', 'unittesting.pytest', 'unittesting.unittest'], ['use.python.most'], ['web.frameworks.Bottle', 'web.frameworks.CherryPy\xa0', 'web.frameworks.Django', 'web.frameworks.Falcon', 'web.frameworks.FastAPI', 'web.frameworks.Flask\xa0', 'web.frameworks.Hug', 'web.frameworks.None', 'web.frameworks.Other', 'web.frameworks.Pyramid\xa0', 'web.frameworks.Tornado', 'web.frameworks.web2py'], ['years.of.coding']])

In [54]:
uniq_cols = []
for cols in counter.values():
    if len(cols) == 1:
        uniq_cols.extend(cols)

In [55]:
uniq_cols

['age',
 'are.you.datascientist',
 'company.size',
 'country.live',
 'employment.status',
 'first.learn.about.main.ide',
 'how.often.use.main.ide',
 'ide.main',
 'is.python.main',
 'job.team',
 'main.purposes',
 'missing.features.main.ide',
 'nps.main.ide',
 'python.years',
 'python2.version.most',
 'python3.version.most',
 'several.projects',
 'team.size',
 'use.python.most',
 'years.of.coding']

In [58]:
len(uniq_cols)

20

- Column names have a period in them. Replace those with underscore as it will allow us to access the names of the columns via attributes

In [57]:
jb[uniq_cols].shape

(54462, 20)

In [59]:
jb[uniq_cols].rename(columns = lambda c:c.replace('.', '_'))

,age,are_you_datascientist,company_size,country_live,employment_status,first_learn_about_main_ide,how_often_use_main_ide,ide_main,is_python_main,job_team,main_purposes,missing_features_main_ide,nps_main_ide,python_years,python2_version_most,python3_version_most,several_projects,team_size,use_python_most,years_of_coding
0,30–39,NaN,Just me,NaN,Partially employed by a company / organization,Conference / User Group,Weekly,PyCharm Community Edition,Yes,Work as an external consultant or trainer,For work,"No, it has all the features I need",3.0,3–5 years,NaN,Python 3_7,"Yes, I work on many different projects",NaN,NaN,1–2 years
1,21–29,Yes,"More than 5,000",India,Fully employed by a company / organization,School / University,Daily,VS Code,Yes,Work in a team,Both for work and personal,"No, it has all the features I need",8.0,3–5 years,NaN,Python 3_6,"Yes, I work on one main and several side projects",2-7 people,Software prototyping,3–5 years
2,30–39,No,"More than 5,000",United States,Fully employed by a company / organization,Friend / Colleague,Daily,Vim,Yes,Work on your own project(s) independently,Both for work and personal,"No, it has all the features I need",10.0,3–5 years,NaN,Python 3_6,"Yes, I work on one main and several side projects",NaN,DevOps / System administration / Writing autom...,3–5 years
3,NaN,NaN,NaN,NaN,NaN,Friend / Colleague,Daily,PyCharm Professional Edition,Yes,NaN,Both for work and personal,Yes – Please list:,10.0,11+ years,NaN,Python 3_8,"Yes, I work on many different projects",NaN,Web development,11+ years
4,21–29,NaN,NaN,Italy,Student,Search engines,Daily,VS Code,Yes,Work on your own project(s) independently,"For personal, educational or side projects","No, it has all the features I need",10.0,1–2 years,NaN,Python 3_8,"Yes, I work on one main and several side projects",NaN,Web development,Less than 1 year
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54457,21–29,No,2–10,Russian Federation,Fully employed by a company / organization,School / University,Daily,Vim,Yes,Work on your own project(s) independently,Both for work and personal,"No, it has all the features I need",10.0,6–10 years,NaN,Python 3_6,"Yes, I work on many different projects",NaN,Data analysis,1–2 years
54458,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,Yes,NaN,Both for work and personal,NaN,NaN,3–5 years,NaN,Python 3_7,NaN,NaN,Web development,1–2 years
54459,21–29,NaN,Just me,Russian Federation,Self-employed (a person earning income directl...,Friend / Colleague,Daily,PyCharm Professional Edition,Yes,Work in a team,Both for work and personal,"No, it has all the features I need",10.0,3–5 years,NaN,Python 3_7,"Yes, I work on many different projects",2-7 people,Web development,6–10 years
54460,30–39,Yes,51–500,Spain,Fully employed by a company / organization,Search engines,Daily,Other,Yes,Work on your own project(s) independently,Both for work and personal,Yes – Please list:,3.0,6–10 years,NaN,Python 3_7,"Yes, I work on many different projects",NaN,Data analysis,3–5 years
54461,21–29,NaN,11–50,Algeria,Fully employed by a company / organization,Online learning platform / Online course,Daily,VS Code,Yes,Work in a team,Both for work and personal,"No, it has all the features I need",10.0,1–2 years,NaN,Python 3_8,"Yes, I work on many different projects",2-7 people,NaN,1–2 years

In [66]:
df = pd.DataFrame({"A": [1, 2, 3], "B": [4, 5, 6]})
df

   A  B
0  1  4
1  2  5
2  3  6

In [68]:
df.rename(str.lower, axis = 'columns')

   a  b
0  1  4
1  2  5
2  3  6

In [69]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [71]:
df.rename(str, axis = 'index').index

Index(['0', '1', '2'], dtype='object')

In [74]:
df.rename(index=lambda x: 2*x).index

Index([0, 2, 4], dtype='int64')

In [79]:
jb[uniq_cols].rename(columns=lambda c: c.replace('.', '_')).age.value_counts()

age
21–29          9710
30–39          7512
40–49          3010
18–20          2567
50–59          1374
60 or older     588
Name: count, dtype: int64

In [80]:
jb[uniq_cols].rename(columns=lambda c: c.replace('.', '_')).age.value_counts(dropna=False)

age
NaN            29701
21–29           9710
30–39           7512
40–49           3010
18–20           2567
50–59           1374
60 or older      588
Name: count, dtype: int64

In [ ]:
(jb
[uniq_cols]
.rename(columns=lambda c: c.replace('.', '_'))
.age
.value_counts(dropna=False))

NaN            29701
21–29           9710
30–39           7512
40–49           3010
18–20           2567
50–59           1374
60 or older      588
Name: age, dtype: int64

- Pull out the first two characters from the ``age`` column and convert it to numbers
- We will have to convert it to float because there are missing values

In [84]:
jb[uniq_cols].rename(columns=lambda c: c.replace('.', '_')).age

0        30–39
1        21–29
2        30–39
3          NaN
4        21–29
         ...
54457    21–29
54458      NaN
54459    21–29
54460    30–39
54461    21–29
Name: age, Length: 54462, dtype: object

In [87]:
jb[uniq_cols].rename(columns=lambda c: c.replace('.', '_')).age.str.slice(0,2)

0         30
1         21
2         30
3        NaN
4         21
        ...
54457     21
54458    NaN
54459     21
54460     30
54461     21
Name: age, Length: 54462, dtype: object

In [88]:
jb[uniq_cols].rename(columns=lambda c: c.replace('.', '_')).age[0]

'30–39'

In [95]:
'30-39'.split('-')

['30', '39']

In [94]:
jb[uniq_cols].rename(columns=lambda c: c.replace('.', '_')).age.iloc[0].split('-')

['30–39']

In [108]:
jb[uniq_cols].rename(columns=lambda c: c.replace('.', '_')).age.str.split('–')[0][0]

'30'

In [103]:
tmp_df = pd.DataFrame({'a':[1,2,3], 'b':[4,5,6]}, index = ['m','n','p'])
tmp_df

   a  b
m  1  4
n  2  5
p  3  6

In [106]:
tmp_df['a'].iloc[0]

1

In [107]:
tmp_df.a.loc['m']

1

In [110]:
jb[uniq_cols].rename(columns=lambda c: c.replace('.', '_')).age.str.slice(0,2).astype(float).astype('Int64')

0          30
1          21
2          30
3        <NA>
4          21
         ...
54457      21
54458    <NA>
54459      21
54460      30
54461      21
Name: age, Length: 54462, dtype: Int64

In [ ]:
(jb
[uniq_cols]
.rename(columns=lambda c: c.replace('.', '_'))
.age
.str.slice(0,2) # or .str[0:2]
.astype(float)
.astype('Int64'))

0          30
1          21
2          30
3        <NA>
4          21
         ...
54457      21
54458    <NA>
54459      21
54460      30
54461      21
Name: age, Length: 54462, dtype: Int64

- Put the cleaned column in dataframe using ``.assign`` method

In [111]:
# 1. Pull out the columns we want
# 2. Rename the columns
# 3. Update the age column

(jb[uniq_cols].rename(columns=lambda c: c.replace('.', '_'))
.assign(age=lambda df_:df_.age
                          .str.slice(0,2) # or .str[0:2]
                          .astype(float)
                          .astype('Int64'))
)

,age,are_you_datascientist,company_size,country_live,employment_status,first_learn_about_main_ide,how_often_use_main_ide,ide_main,is_python_main,job_team,main_purposes,missing_features_main_ide,nps_main_ide,python_years,python2_version_most,python3_version_most,several_projects,team_size,use_python_most,years_of_coding
0,30,NaN,Just me,NaN,Partially employed by a company / organization,Conference / User Group,Weekly,PyCharm Community Edition,Yes,Work as an external consultant or trainer,For work,"No, it has all the features I need",3.0,3–5 years,NaN,Python 3_7,"Yes, I work on many different projects",NaN,NaN,1–2 years
1,21,Yes,"More than 5,000",India,Fully employed by a company / organization,School / University,Daily,VS Code,Yes,Work in a team,Both for work and personal,"No, it has all the features I need",8.0,3–5 years,NaN,Python 3_6,"Yes, I work on one main and several side projects",2-7 people,Software prototyping,3–5 years
2,30,No,"More than 5,000",United States,Fully employed by a company / organization,Friend / Colleague,Daily,Vim,Yes,Work on your own project(s) independently,Both for work and personal,"No, it has all the features I need",10.0,3–5 years,NaN,Python 3_6,"Yes, I work on one main and several side projects",NaN,DevOps / System administration / Writing autom...,3–5 years
3,<NA>,NaN,NaN,NaN,NaN,Friend / Colleague,Daily,PyCharm Professional Edition,Yes,NaN,Both for work and personal,Yes – Please list:,10.0,11+ years,NaN,Python 3_8,"Yes, I work on many different projects",NaN,Web development,11+ years
4,21,NaN,NaN,Italy,Student,Search engines,Daily,VS Code,Yes,Work on your own project(s) independently,"For personal, educational or side projects","No, it has all the features I need",10.0,1–2 years,NaN,Python 3_8,"Yes, I work on one main and several side projects",NaN,Web development,Less than 1 year
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54457,21,No,2–10,Russian Federation,Fully employed by a company / organization,School / University,Daily,Vim,Yes,Work on your own project(s) independently,Both for work and personal,"No, it has all the features I need",10.0,6–10 years,NaN,Python 3_6,"Yes, I work on many different projects",NaN,Data analysis,1–2 years
54458,<NA>,No,NaN,NaN,NaN,NaN,NaN,NaN,Yes,NaN,Both for work and personal,NaN,NaN,3–5 years,NaN,Python 3_7,NaN,NaN,Web development,1–2 years
54459,21,NaN,Just me,Russian Federation,Self-employed (a person earning income directl...,Friend / Colleague,Daily,PyCharm Professional Edition,Yes,Work in a team,Both for work and personal,"No, it has all the features I need",10.0,3–5 years,NaN,Python 3_7,"Yes, I work on many different projects",2-7 people,Web development,6–10 years
54460,30,Yes,51–500,Spain,Fully employed by a company / organization,Search engines,Daily,Other,Yes,Work on your own project(s) independently,Both for work and personal,Yes – Please list:,3.0,6–10 years,NaN,Python 3_7,"Yes, I work on many different projects",NaN,Data analysis,3–5 years
54461,21,NaN,11–50,Algeria,Fully employed by a company / organization,Online learning platform / Online course,Daily,VS Code,Yes,Work in a team,Both for work and personal,"No, it has all the features I need",10.0,1–2 years,NaN,Python 3_8,"Yes, I work on many different projects",2-7 people,NaN,1–2 years

## 21.2 More Column Cleanup

- Convert the ``are_you_datascientist`` column to a boolean columns

In [114]:
jb[uniq_cols].rename(columns=lambda c: c.replace('.', '_')).are_you_datascientist

0        NaN
1        Yes
2         No
3        NaN
4        NaN
        ...
54457     No
54458     No
54459    NaN
54460    Yes
54461    NaN
Name: are_you_datascientist, Length: 54462, dtype: object

In [121]:
type(jb[uniq_cols].rename(columns=lambda c: c.replace('.', '_')).are_you_datascientist.iloc[0])

float

In [122]:
type(jb[uniq_cols].rename(columns=lambda c: c.replace('.', '_')).are_you_datascientist.iloc[2])

str

In [123]:
jb[uniq_cols].rename(columns=lambda c: c.replace('.', '_')).are_you_datascientist.replace({'Yes':True, 'No':False, 'NaN': np.nan})

0          NaN
1         True
2        False
3          NaN
4          NaN
         ...
54457    False
54458    False
54459      NaN
54460     True
54461      NaN
Name: are_you_datascientist, Length: 54462, dtype: object

In [116]:
jb[uniq_cols].rename(columns=lambda c: c.replace('.', '_')).iloc[0]

age                                                                    30–39
are_you_datascientist                                                    NaN
company_size                                                         Just me
country_live                                                             NaN
employment_status             Partially employed by a company / organization
first_learn_about_main_ide                           Conference / User Group
how_often_use_main_ide                                                Weekly
ide_main                                           PyCharm Community Edition
is_python_main                                                           Yes
job_team                           Work as an external consultant or trainer
main_purposes                                                       For work
missing_features_main_ide                 No, it has all the features I need
nps_main_ide                                                             3.0
python_years                                                       3–5 years
python2_version_most                                                     NaN
python3_version_most                                              Python 3_7
several_projects                      Yes, I work on many different projects
team_size                                                                NaN
use_python_most                                                          NaN
years_of_coding                                                    1–2 years
Name: 0, dtype: object

In [ ]:
(jb
[uniq_cols]
.rename(columns=lambda c: c.replace('.', '_'))
.assign(age=lambda df_:df_.age
                          .str.slice(0,2) # or .str[0:2]
                          .astype(float)
                          .astype('Int64'),
        are_you_datascientist=lambda df_: df_.are_you_datascientist
                                             .replace({'Yes': True,
                                                       'No': False,
                                                       np.nan: False})
)
.are_you_datascientist
)

0        False
1         True
2        False
3        False
4        False
         ...
54457    False
54458    False
54459    False
54460     True
54461    False
Name: are_you_datascientist, Length: 54462, dtype: object

In [128]:
(jb
[uniq_cols]
.rename(columns=lambda c: c.replace('.', '_'))
.assign(age=lambda df_:df_.age
                          .str.slice(0,2) # or .str[0:2]
                          .astype(float)
                          .astype('Int64'),
        are_you_datascientist=lambda df_: df_.are_you_datascientist
                                             .replace({'Yes': True,
                                                       'No': False,
                                                       np.nan: False})
)).head().company_size

0            Just me
1    More than 5,000
2    More than 5,000
3                NaN
4                NaN
Name: company_size, dtype: object

- Look at ``company_size``

In [129]:
(jb
[uniq_cols]
.rename(columns=lambda c: c.replace('.', '_'))
.assign(age=lambda df_:df_.age
                          .str.slice(0,2) # or .str[0:2]
                          .astype(float)
                          .astype('Int64'),
        are_you_datascientist=lambda df_: df_.are_you_datascientist
                                             .replace({'Yes': True,
                                                       'No': False,
                                                       np.nan: False})
)
.company_size
.value_counts(dropna=False)
)

company_size
NaN                35037
51–500              4608
More than 5,000     3635
11–50               3507
2–10                2558
1,001–5,000         1934
Just me             1492
501–1,000           1165
Not sure             526
Name: count, dtype: int64

In [150]:
(jb
[uniq_cols]
.rename(columns=lambda c: c.replace('.', '_'))
).select_dtypes('object')

,age,are_you_datascientist,company_size,country_live,employment_status,first_learn_about_main_ide,how_often_use_main_ide,ide_main,is_python_main,job_team,main_purposes,missing_features_main_ide,python_years,python2_version_most,python3_version_most,several_projects,team_size,use_python_most,years_of_coding
0,30–39,NaN,Just me,NaN,Partially employed by a company / organization,Conference / User Group,Weekly,PyCharm Community Edition,Yes,Work as an external consultant or trainer,For work,"No, it has all the features I need",3–5 years,NaN,Python 3_7,"Yes, I work on many different projects",NaN,NaN,1–2 years
1,21–29,Yes,"More than 5,000",India,Fully employed by a company / organization,School / University,Daily,VS Code,Yes,Work in a team,Both for work and personal,"No, it has all the features I need",3–5 years,NaN,Python 3_6,"Yes, I work on one main and several side projects",2-7 people,Software prototyping,3–5 years
2,30–39,No,"More than 5,000",United States,Fully employed by a company / organization,Friend / Colleague,Daily,Vim,Yes,Work on your own project(s) independently,Both for work and personal,"No, it has all the features I need",3–5 years,NaN,Python 3_6,"Yes, I work on one main and several side projects",NaN,DevOps / System administration / Writing autom...,3–5 years
3,NaN,NaN,NaN,NaN,NaN,Friend / Colleague,Daily,PyCharm Professional Edition,Yes,NaN,Both for work and personal,Yes – Please list:,11+ years,NaN,Python 3_8,"Yes, I work on many different projects",NaN,Web development,11+ years
4,21–29,NaN,NaN,Italy,Student,Search engines,Daily,VS Code,Yes,Work on your own project(s) independently,"For personal, educational or side projects","No, it has all the features I need",1–2 years,NaN,Python 3_8,"Yes, I work on one main and several side projects",NaN,Web development,Less than 1 year
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54457,21–29,No,2–10,Russian Federation,Fully employed by a company / organization,School / University,Daily,Vim,Yes,Work on your own project(s) independently,Both for work and personal,"No, it has all the features I need",6–10 years,NaN,Python 3_6,"Yes, I work on many different projects",NaN,Data analysis,1–2 years
54458,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,Yes,NaN,Both for work and personal,NaN,3–5 years,NaN,Python 3_7,NaN,NaN,Web development,1–2 years
54459,21–29,NaN,Just me,Russian Federation,Self-employed (a person earning income directl...,Friend / Colleague,Daily,PyCharm Professional Edition,Yes,Work in a team,Both for work and personal,"No, it has all the features I need",3–5 years,NaN,Python 3_7,"Yes, I work on many different projects",2-7 people,Web development,6–10 years
54460,30–39,Yes,51–500,Spain,Fully employed by a company / organization,Search engines,Daily,Other,Yes,Work on your own project(s) independently,Both for work and personal,Yes – Please list:,6–10 years,NaN,Python 3_7,"Yes, I work on many different projects",NaN,Data analysis,3–5 years
54461,21–29,NaN,11–50,Algeria,Fully employed by a company / organization,Online learning platform / Online course,Daily,VS Code,Yes,Work in a team,Both for work and personal,"No, it has all the features I need",1–2 years,NaN,Python 3_8,"Yes, I work on many different projects",2-7 people,NaN,1–2 years

In [156]:
(jb
[uniq_cols]
.rename(columns=lambda c: c.replace('.', '_'))
.assign(**{col:df[col].astype(float)
              for col in df.select_dtypes('number')},
        **{col:df[col].astype(str).fillna('')
              for col in df.select_dtypes(['object', 'category'])})

).company_size.dtype

dtype('O')

In [134]:
jb2 = (jb
 [uniq_cols]
 .rename(columns=lambda c: c.replace('.', '_'))
 .assign(age=lambda df_:df_.age.str.slice(0,2).astype(float)
             .astype('Int64'),
         are_you_datascientist=lambda df_:df_.are_you_datascientist
             .replace({'Yes': True, 'No': False, np.nan: False}),
         company_size=lambda df_:df_.company_size.replace({
             'Just me': 1, 'Not sure': np.nan,
             'More than 5,000': 5000, '2–10': 2, '11–50':11,
             '51–500': 51, '501–1,000':501,
             '1,001–5,000':1001}).astype('Int64'),
         country_live=lambda df_:df_.country_live.astype('category'),
         employment_status=lambda df_:df_.employment_status
              .fillna('Other').astype('category'),
         is_python_main=lambda df_:df_.is_python_main
              .astype('category'),
         team_size=lambda df_:df_.team_size
             .str.split(r'-', n=1, expand=True)
             .iloc[:,0].replace('More than 40 people', 41)
             .where(df_.company_size!=1, 1).astype(float),
         years_of_coding=lambda df_:df_.years_of_coding
             .replace('Less than 1 year', .5).str.extract(r'(\d+)')
             .astype(float),
         python_years=lambda df_:df_.python_years
             .replace('Less than 1 year', .5).str.extract(r'(\d+)')
             .astype(float),
         python3_ver=lambda df_:df_.python3_version_most
              .str.replace('_', '.').str.extract(r'(\d\.\d)')
              .astype(float),
         use_python_most=lambda df_:df_.use_python_most
              .fillna('Unknown')
        )
    .drop(columns=['python2_version_most'])
)

<ipython-input-134-9a7be5d47f1d>:8: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  company_size=lambda df_:df_.company_size.replace({

In [133]:
jb2

,age,are_you_datascientist,company_size,country_live,employment_status,first_learn_about_main_ide,how_often_use_main_ide,ide_main,is_python_main,job_team,...,missing_features_main_ide,nps_main_ide,python_years,python2_version_most,python3_version_most,several_projects,team_size,use_python_most,years_of_coding,python3_ver
0,30,False,1,NaN,Partially employed by a company / organization,Conference / User Group,Weekly,PyCharm Community Edition,Yes,Work as an external consultant or trainer,...,"No, it has all the features I need",3.0,3.0,NaN,Python 3_7,"Yes, I work on many different projects",1.0,Unknown,1.0,3.7
1,21,True,5000,India,Fully employed by a company / organization,School / University,Daily,VS Code,Yes,Work in a team,...,"No, it has all the features I need",8.0,3.0,NaN,Python 3_6,"Yes, I work on one main and several side projects",2.0,Software prototyping,3.0,3.6
2,30,False,5000,United States,Fully employed by a company / organization,Friend / Colleague,Daily,Vim,Yes,Work on your own project(s) independently,...,"No, it has all the features I need",10.0,3.0,NaN,Python 3_6,"Yes, I work on one main and several side projects",NaN,DevOps / System administration / Writing autom...,3.0,3.6
3,<NA>,False,<NA>,NaN,Other,Friend / Colleague,Daily,PyCharm Professional Edition,Yes,NaN,...,Yes – Please list:,10.0,11.0,NaN,Python 3_8,"Yes, I work on many different projects",1.0,Web development,11.0,3.8
4,21,False,<NA>,Italy,Student,Search engines,Daily,VS Code,Yes,Work on your own project(s) independently,...,"No, it has all the features I need",10.0,1.0,NaN,Python 3_8,"Yes, I work on one main and several side projects",1.0,Web development,NaN,3.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54457,21,False,2,Russian Federation,Fully employed by a company / organization,School / University,Daily,Vim,Yes,Work on your own project(s) independently,...,"No, it has all the features I need",10.0,6.0,NaN,Python 3_6,"Yes, I work on many different projects",NaN,Data analysis,1.0,3.6
54458,<NA>,False,<NA>,NaN,Other,NaN,NaN,NaN,Yes,NaN,...,NaN,NaN,3.0,NaN,Python 3_7,NaN,1.0,Web development,1.0,3.7
54459,21,False,1,Russian Federation,Self-employed (a person earning income directl...,Friend / Colleague,Daily,PyCharm Professional Edition,Yes,Work in a team,...,"No, it has all the features I need",10.0,3.0,NaN,Python 3_7,"Yes, I work on many different projects",1.0,Web development,6.0,3.7
54460,30,True,51,Spain,Fully employed by a company / organization,Search engines,Daily,Other,Yes,Work on your own project(s) independently,...,Yes – Please list:,3.0,6.0,NaN,Python 3_7,"Yes, I work on many different projects",NaN,Data analysis,3.0,3.7
54461,21,False,11,Algeria,Fully employed by a company / organization,Online learning platform / Online course,Daily,VS Code,Yes,Work in a team,...,"No, it has all the features I need",10.0,1.0,NaN,Python 3_8,"Yes, I work on many different projects",2.0,Unknown,1.0,3.8

In [136]:
jb2.team_size.head()

0    1.0
1    2.0
2    NaN
3    1.0
4    1.0
Name: team_size, dtype: float64

In [138]:
jb2.query('team_size.isna()').employment_status

2            Fully employed by a company / organization
14           Fully employed by a company / organization
16                                      Working student
17           Fully employed by a company / organization
25           Fully employed by a company / organization
                              ...
54431        Fully employed by a company / organization
54445    Partially employed by a company / organization
54456        Fully employed by a company / organization
54457        Fully employed by a company / organization
54460        Fully employed by a company / organization
Name: employment_status, Length: 6887, dtype: category
Categories (8, object): ['Freelancer (a person pursuing a profession wi..., 'Fully employed by a company / organization', 'Other',
                         'Partially employed by a company / organization', 'Retired',
                         'Self-employed (a person earning income direct..., 'Student', 'Working student']

In [140]:
jb2.query('team_size.isna()').employment_status

2            Fully employed by a company / organization
14           Fully employed by a company / organization
16                                      Working student
17           Fully employed by a company / organization
25           Fully employed by a company / organization
                              ...
54431        Fully employed by a company / organization
54445    Partially employed by a company / organization
54456        Fully employed by a company / organization
54457        Fully employed by a company / organization
54460        Fully employed by a company / organization
Name: employment_status, Length: 6887, dtype: category
Categories (8, object): ['Freelancer (a person pursuing a profession wi..., 'Fully employed by a company / organization', 'Other',
                         'Partially employed by a company / organization', 'Retired',
                         'Self-employed (a person earning income direct..., 'Student', 'Working student']

- Taking a closer look at ``team_size``

In [141]:
(jb2
.query('team_size.isna()') # filter team_size == na
.employment_status
.value_counts(dropna=False)
)

employment_status
Fully employed by a company / organization                                                        5279
Working student                                                                                    696
Partially employed by a company / organization                                                     482
Self-employed (a person earning income directly from one's own business, trade, or profession)     430
Freelancer (a person pursuing a profession without a long-term commitment to any one employer)       0
Other                                                                                                0
Retired                                                                                              0
Student                                                                                              0
Name: count, dtype: int64

- Call ``.assign`` to use machine learning to predict the missing values for that column by leveraging CatBoost library (Category Boosting)
- A nice feature of this library is that it will accept missing values and also string values
- CatBoost doesn't like native pandas type ('Int64', 'category') so we will make a function ``prep_for_ml``

In [143]:
pip install catboost

Collecting catboost
  Downloading catboost-1.2.7-cp311-cp311-manylinux2014_x86_64.whl.metadata (1.2 kB)
Requirement already satisfied: graphviz in /usr/local/lib/python3.11/dist-packages (from catboost) (0.20.3)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.11/dist-packages (from catboost) (3.10.0)
Requirement already satisfied: numpy<2.0,>=1.16.0 in /usr/local/lib/python3.11/dist-packages (from catboost) (1.26.4)
Requirement already satisfied: pandas>=0.24 in /usr/local/lib/python3.11/dist-packages (from catboost) (2.2.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.11/dist-packages (from catboost) (1.13.1)
Requirement already satisfied: plotly in /usr/local/lib/python3.11/dist-packages (from catboost) (5.24.1)
Requirement already satisfied: six in /usr/local/lib/python3.11/dist-packages (from catboost) (1.17.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas>=0.24->catboost) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas>=0.24->catboost) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas>=0.24->catboost) (2025.1)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib->catboost) (1.3.1)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.11/dist-packages (from matplotlib->catboost) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib->catboost) (4.55.7)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib->catboost) (1.4.8)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib->catboost) (24.2)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.11/dist-packages (from matplotlib->catboost) (11.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib->catboost) (3.2.1)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.11/dist-packages (from plotly->catboost) (9.0.0)
Downloading catboost-1.2.7-cp311-cp311-manylinux2014_x86_64.whl (98.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 98.7/98.7 MB 8.3 MB/s eta 0:00:00
Installing collected packages: catboost
Successfully installed catboost-1.2.7

In [144]:
import catboost as cb
import numpy as np

In [145]:
def prep_for_ml(df):
    # remove pandas types
    return (df
    .assign(**{col:df[col].astype(float)
              for col in df.select_dtypes('number')},
            **{col:df[col].astype(str).fillna('')
              for col in df.select_dtypes(['object', 'category'])}))

In [157]:
def predict_col(df, col):
    df = prep_for_ml(df)
    missing = df.query(f'~{col}.isna()')
    cat_idx = [i for i,typ in enumerate(df.drop(columns=[col]).dtypes)
               if str(typ) == 'object']
    X = (missing
         .drop(columns=[col])
         .values
        )
    y = missing[col]
    model = cb.CatBoostRegressor(iterations=20, cat_features=cat_idx)
    model.fit(X,y, cat_features=cat_idx)
    pred = model.predict(df.drop(columns=[col]))
    return df[col].where(~df[col].isna(), pred)

In [158]:
jb2 = (jb
  [uniq_cols]
  .rename(columns=lambda c: c.replace('.', '_'))
  .assign(age=lambda df_:df_.age.str.slice(0,2).astype(float)
             .astype('Int64'),
         are_you_datascientist=lambda df_:df_.are_you_datascientist
             .replace({'Yes': True, 'No': False, np.nan: False}),
         company_size=lambda df_:df_.company_size.replace({
             'Just me': 1, 'Not sure': np.nan,
             'More than 5,000': 5000, '2–10': 2, '11–50':11,
             '51–500': 51, '501–1,000':501,
             '1,001–5,000':1001}).astype('Int64'),
         country_live=lambda df_:df_.country_live.astype('category'),
         employment_status=lambda df_:df_.employment_status
              .fillna('Other').astype('category'),
         is_python_main=lambda df_:df_.is_python_main
              .astype('category'),
         team_size=lambda df_:df_.team_size
             .str.split(r'-', n=1, expand=True)
             .iloc[:,0].replace('More than 40 people', 41)
             .where(df_.company_size!=1, 1).astype(float),
         years_of_coding=lambda df_:df_.years_of_coding
             .replace('Less than 1 year', .5).str.extract(r'(\d+)')
             .astype(float),
         python_years=lambda df_:df_.python_years
             .replace('Less than 1 year', .5).str.extract(r'(\d+)')
             .astype(float),
         python3_ver=lambda df_:df_.python3_version_most
              .str.replace('_', '.').str.extract(r'(\d\.\d)')
              .astype(float),
         use_python_most=lambda df_:df_.use_python_most
              .fillna('Unknown')
        )
  .assign(team_size=lambda df_:predict_col(df_, 'team_size')
          .astype(int))
  .drop(columns=['python2_version_most'])
  .dropna()
)

<ipython-input-158-16d337da3bdb>:8: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  company_size=lambda df_:df_.company_size.replace({

Learning rate set to 0.5
0:	learn: 2.9695218	total: 134ms	remaining: 2.54s
1:	learn: 2.8766539	total: 196ms	remaining: 1.76s
2:	learn: 2.8387189	total: 269ms	remaining: 1.52s
3:	learn: 2.8028751	total: 340ms	remaining: 1.36s
4:	learn: 2.7899957	total: 413ms	remaining: 1.24s
5:	learn: 2.7749439	total: 482ms	remaining: 1.13s
6:	learn: 2.7719128	total: 554ms	remaining: 1.03s
7:	learn: 2.7649792	total: 631ms	remaining: 947ms
8:	learn: 2.7649588	total: 685ms	remaining: 837ms
9:	learn: 2.7630617	total: 761ms	remaining: 761ms
10:	learn: 2.7625779	total: 836ms	remaining: 684ms
11:	learn: 2.7515902	total: 902ms	remaining: 602ms
12:	learn: 2.7513459	total: 975ms	remaining: 525ms
13:	learn: 2.7445634	total: 1.04s	remaining: 446ms
14:	learn: 2.7443257	total: 1.1s	remaining: 369ms
15:	learn: 2.7423142	total: 1.18s	remaining: 294ms
16:	learn: 2.7419144	total: 1.25s	remaining: 220ms
17:	learn: 2.7399388	total: 1.31s	remaining: 146ms
18:	learn: 2.7384297	total: 1.38s	remaining: 72.8ms
19:	learn: 2.7383591	total: 1.44s	remaining: 0us

In [ ]:
jb2

,age,are_you_datascientist,company_size,country_live,employment_status,first_learn_about_main_ide,how_often_use_main_ide,ide_main,is_python_main,job_team,main_purposes,missing_features_main_ide,nps_main_ide,python_years,python3_version_most,several_projects,team_size,use_python_most,years_of_coding,python3_ver
1,21,True,5000,India,Fully employed by a company / organization,School / University,Daily,VS Code,Yes,Work in a team,Both for work and personal,"No, it has all the features I need",8.0,3.0,Python 3_6,"Yes, I work on one main and several side projects",2,Software prototyping,3.0,3.6
2,30,False,5000,United States,Fully employed by a company / organization,Friend / Colleague,Daily,Vim,Yes,Work on your own project(s) independently,Both for work and personal,"No, it has all the features I need",10.0,3.0,Python 3_6,"Yes, I work on one main and several side projects",4,DevOps / System administration / Writing autom...,3.0,3.6
10,21,False,51,Other country,Fully employed by a company / organization,School / University,Daily,IntelliJ IDEA,Yes,Work in a team,Both for work and personal,"No, it has all the features I need",10.0,1.0,Python 3_8,"Yes, I work on one main and several side projects",2,Web development,1.0,3.8
11,21,True,51,United States,Fully employed by a company / organization,Online learning platform / Online course,Daily,PyCharm Community Edition,Yes,Work in a team,Both for work and personal,"No, it has all the features I need",9.0,3.0,Python 3_9,"Yes, I work on many different projects",2,Data analysis,3.0,3.9
13,30,True,5000,Belgium,Fully employed by a company / organization,Social network,Daily,VS Code,Yes,Work in a team,Both for work and personal,"No, it has all the features I need",10.0,6.0,Python 3_7,"Yes, I work on many different projects",2,Data analysis,3.0,3.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54456,30,False,1001,Turkey,Fully employed by a company / organization,Friend / Colleague,Daily,PyCharm Community Edition,Yes,Work on your own project(s) independently,Both for work and personal,"No, it has all the features I need",9.0,1.0,Python 3_6,"Yes, I work on many different projects",5,Machine learning,6.0,3.6
54457,21,False,2,Russian Federation,Fully employed by a company / organization,School / University,Daily,Vim,Yes,Work on your own project(s) independently,Both for work and personal,"No, it has all the features I need",10.0,6.0,Python 3_6,"Yes, I work on many different projects",2,Data analysis,1.0,3.6
54459,21,False,1,Russian Federation,Self-employed (a person earning income directl...,Friend / Colleague,Daily,PyCharm Professional Edition,Yes,Work in a team,Both for work and personal,"No, it has all the features I need",10.0,3.0,Python 3_7,"Yes, I work on many different projects",1,Web development,6.0,3.7
54460,30,True,51,Spain,Fully employed by a company / organization,Search engines,Daily,Other,Yes,Work on your own project(s) independently,Both for work and personal,Yes – Please list:,3.0,6.0,Python 3_7,"Yes, I work on many different projects",4,Data analysis,3.0,3.7
54461,21,False,11,Algeria,Fully employed by a company / organization,Online learning platform / Online course,Daily,VS Code,Yes,Work in a team,Both for work and personal,"No, it has all the features I need",10.0,1.0,Python 3_8,"Yes, I work on many different projects",2,Unknown,1.0,3.8